version: "3"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "80:8080"
